

DROP USER AhmadMM10;
CREATE USER AhmadMM10
IDENTIFIED BY MOONmoon24633
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to AhmadMM10;
GRANT resource to AhmadMM10;
GRANT create session TO AhmadMM10;
GRANT create table TO AhmadMM10;
GRANT create view TO AhmadMM10;

conn AhmadMM10/MOONmoon24633


CREATE TABLE USER1(
USERNAME VARCHAR(50),
PASSWORD1 VARCHAR(50));

CREATE TABLE CARS(
CAR_MAKE VARCHAR2(50),
CAR_MODEL VARCHAR2(50),
CAR_YEAR INTEGER,
CAR_PRICE INTEGER,
CAR_STATUS VARCHAR2(20),
CAR_ID INTEGER PRIMARY KEY,
CAR_OWNER VARCHAR2(20));

CREATE TABLE OFFERS(
CAR_ID INTEGER,
USERNAME VARCHAR(50),
CAR_MAKE VARCHAR(50),
CAR_MODEL VARCHAR(50),
CAR_YEAR INTEGER,
CAR_PRICE INTEGER,
NUMBER_OF_MONTHS INTEGER );

CREATE TABLE PAYMENTS(
CAR_ID INTEGER,
PAYMENTS_DECIDED INTEGER,
REMAINING_PAYMENTS INTEGER,
CAR_PRICE INTEGER,
AMOUNT_REMAINING INTEGER,
USERNAME VARCHAR(50));

CREATE TABLE EMPLOYEE(
EMPLOYEE_NAME VARCHAR(50),
EMP_PASSWORD VARCHAR(50));

ALTER TABLE OFFERS
ADD FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID);

ALTER TABLE PAYMENTS
ADD FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID);